FROM fedora:41

RUN yum -y install nginx php-fpm

RUN mkdir /nginx_php

COPY conf/nginx.conf /etc/nginx/conf.d/default.conf

COPY fruit /nginx_php

COPY test.php /nginx_php

COPY conf/start.sh /start.sh

RUN chmod +x /start.sh

CMD  /start.sh
